/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.89
 * Generated at: 2023-06-18 04:09:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.publicWeb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class managementFunding_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"react-view\" class=\"tbb-only-ff\">\r\n");
      out.write("		<div class=\"ScrollTop__ScrollTopBtnWrapper-j9uqn7-1 bUyjJv\">\r\n");
      out.write("			<button class=\"ScrollTop__ScrollTopBtn-j9uqn7-2 ioLFRP\">\r\n");
      out.write("				<span>최상위로</span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"ScrollTop__StyledIcon-j9uqn7-0 cfpUR\">\r\n");
      out.write("				<svg width=\"22px\" height=\"18px\" viewBox=\"0 0 22 18\" version=\"1.1\"\r\n");
      out.write("					xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("					<g id=\"Page-1\" stroke=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("					<g id=\"jump-to-top\" transform=\"translate(-1.000000, 0.000000)\">\r\n");
      out.write("					<path\r\n");
      out.write("						d=\"M12.006,5.987 L22.75,16.437 C22.9,16.587 23,16.837 23,17.087 C23,17.338 22.9,17.587 22.7,17.737 C22.35,18.087 21.75,18.087 21.35,17.737 L12.006,8.587 L2.611,17.737 C2.261,18.087 1.662,18.087 1.262,17.737 C0.912,17.387 0.912,16.787 1.262,16.437 L12.006,5.987 L12.006,5.987 Z M22.175,0 C22.631,0 23,0.37 23,0.825 L23,0.877 C23,1.332 22.63,1.702 22.175,1.702 L1.825,1.702 C1.369,1.702 1,1.332 1,0.877 L1,0.825 C1,0.369 1.37,0 1.825,0 L22.175,0 Z\"\r\n");
      out.write("						id=\"Shape\"></path></g></g></svg>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"common-Layer tbb\"></div>\r\n");
      out.write("		<div class=\"style__ProjectEditorWrap-sc-1mawbc1-5 fEFqM\">\r\n");
      out.write("			<div class=\"style__TopContents-sc-1y2waj3-0 jFWgiC top-content\">\r\n");
      out.write("				<div class=\"style__Header-sc-1dvdb02-0 gLzraa\">\r\n");
      out.write("					<div class=\"style__HeaderWrap-sc-1dvdb02-2 fzQQdl\">\r\n");
      out.write("						<a class=\"style__HeaderLeft-sc-1dvdb02-4 jJmDgg\"\r\n");
      out.write("							href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management\"><div\r\n");
      out.write("								name=\"arrow3-left\"\r\n");
      out.write("								class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs style__icon-sc-1dvdb02-3 ggMYrs\">\r\n");
      out.write("								<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("									<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("										d=\"M43.7014 21.7189L10.1221 21.7189L25.2128 7.06878C26.1112 6.15946 26.2122 4.64393 25.3127 3.73461C24.4133 2.82529 22.9142 2.72425 22.0148 3.63357L2.72663 22.4262C1.82719 23.3355 1.72725 24.75 2.62669 25.7604H2.72663L22.0148 44.4519C22.9142 45.2602 24.4133 45.1592 25.2128 44.2499C26.0123 43.3405 26.0123 41.926 25.1119 41.0167L10.0221 26.4676L43.7014 26.4676C45.0006 26.4676 46 25.4572 46 24.1438C46 22.8303 45.0006 21.7189 43.7014 21.7189Z\"></path></svg>\r\n");
      out.write("							</div></a>\r\n");
      out.write("						<div class=\"style__HeaderRight-sc-1dvdb02-5 YPHW\">\r\n");
      out.write("							<button\r\n");
      out.write("								class=\"LineButton__Button-sc-1ozfxit-0 dlhxb style__HeaderButton-sc-1dvdb02-7 bbjjoy pdc-btn-l\"\r\n");
      out.write("								color=\"grayEditor200\">\r\n");
      out.write("								<div name=\"visibility\"\r\n");
      out.write("									class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs style__icon-sc-1dvdb02-3 ggMYrs\">\r\n");
      out.write("									<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("										<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("											d=\"M13.7 23.9943C13.8 29.506 18.4 34.0342 24 33.935C29.6 34.0342 34.2 29.506 34.3 23.9943C34.2 18.4826 29.6 13.9563 24 14.0545C18.4 13.9563 13.8 18.4826 13.7 23.9943ZM2 23.9943C5.5 15.2355 14.4 9.62552 24 10.0195C33.6 9.62552 42.5 15.2355 46 23.9943C42.5 32.8523 33.6 38.4623 24 37.97C14.4 38.364 5.5 32.7541 2 23.9943ZM30.6 23.9944C30.6 20.4614 27.646 17.5974 24 17.5974C20.355 17.5974 17.4 20.4614 17.4 23.9944C17.4 27.5274 20.355 30.3913 24 30.3913C27.646 30.3913 30.6 27.5274 30.6 23.9944Z\"></path></svg>\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"previewText\">미리 보기</span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button\r\n");
      out.write("								class=\"SolidButton__Button-sc-1gsinzz-0 hgsFUp ProjectSubmitButton__ProjectButton-m5pw9c-2 hQPdvE fnt-p1\"\r\n");
      out.write("								disabled=\"\" color=\"white\">\r\n");
      out.write("								<span>기획중·11% 완료</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"style__TopContentsWrap-sc-1y2waj3-1 lhcIOG\">\r\n");
      out.write("					<div class=\"style__Title-sc-1y2waj3-3 iePPZZ\">프로젝트 기획</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"style__FixedContentWrap-sc-1y2waj3-4 gvPBkk\">\r\n");
      out.write("					<div class=\"style__Plan1DepthWrap-sc-1y2waj3-6 cWslIP\">\r\n");
      out.write("						<ul class=\"style__TabItems-sc-1y2waj3-8 cBbdAT\">\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 cqTslV\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/service-plan\">요금제\r\n");
      out.write("									선택</a></li>\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 cqTslV\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/default\">기본정보<span\r\n");
      out.write("									class=\"TabItem__TabStatus-vjb6ta-1 IXvYM\">5</span></a></li>\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 krGOIO\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/funding\">펀딩\r\n");
      out.write("									계획<span class=\"TabItem__TabStatus-vjb6ta-1 IXvYM\">3</span>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 cqTslV\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/reward\">선물\r\n");
      out.write("									구성<span class=\"TabItem__TabStatus-vjb6ta-1 IXvYM\">1</span>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 cqTslV\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/story\">프로젝트\r\n");
      out.write("									계획<span class=\"TabItem__TabStatus-vjb6ta-1 IXvYM\">5</span>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 cqTslV\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/creator\">창작자\r\n");
      out.write("									정보<span class=\"TabItem__TabStatus-vjb6ta-1 IXvYM\">4</span>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li class=\"TabItem__Tab-vjb6ta-0 cqTslV\"><a class=\"\"\r\n");
      out.write("								href=\"/project-editor/32fa41aa-92d2-49b0-b18d-bc4ebd4dfa8b/management/policy\">신뢰와\r\n");
      out.write("									안전<span class=\"TabItem__TabStatus-vjb6ta-1 IXvYM\">2</span>\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"style__Contents-sc-1y2waj3-14 CqQKt\" size=\"228\">\r\n");
      out.write("				<div class=\"style__PlanContents-sc-1mawbc1-6 ghVmvY\">\r\n");
      out.write("					<div class=\"ProjectItem__ProjectItemWrap-sc-1vwy8z0-0 fGfROL\">\r\n");
      out.write("						<dl class=\"ProjectItem__ProjectInfo-sc-1vwy8z0-1 kwDByH\">\r\n");
      out.write("							<dt class=\"ProjectItem__ProjectInfoTitle-sc-1vwy8z0-2 gjLASS\">\r\n");
      out.write("								목표 금액\r\n");
      out.write("								<div name=\"asterisk-solid\"\r\n");
      out.write("									class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("									<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("										<path\r\n");
      out.write("											d=\"M20.332 6.1C20.332 6.04477 20.3768 6 20.432 6H27.1968C27.252 6 27.2968 6.04477 27.2968 6.1V18.2295C27.2968 18.3066 27.3803 18.3547 27.447 18.316L37.8336 12.289C37.8815 12.2612 37.9429 12.2777 37.9705 12.3257L41.3532 18.2144C41.3807 18.2622 41.3643 18.3231 41.3167 18.3507L31.0164 24.3277C30.95 24.3662 30.95 24.4622 31.0164 24.5007L40.8186 30.1886C40.8663 30.2163 40.8826 30.2772 40.8552 30.3249L37.4724 36.2137C37.4448 36.2617 37.3834 36.2782 37.3355 36.2504L27.447 30.5124C27.3803 30.4737 27.2968 30.5218 27.2968 30.5989V41.9C27.2968 41.9552 27.252 42 27.1968 42H20.432C20.3768 42 20.332 41.9552 20.332 41.9V30.7012C20.332 30.6241 20.2485 30.576 20.1818 30.6147L10.4697 36.2504C10.4218 36.2782 10.3604 36.2617 10.3328 36.2137L6.95002 30.3249C6.92259 30.2772 6.93892 30.2163 6.98654 30.1886L16.7888 24.5007C16.8552 24.4622 16.8552 24.3662 16.7888 24.3277L6.48846 18.3508C6.44084 18.3231 6.42451 18.2622 6.45194 18.2144L9.8347 12.3257C9.8623 12.2777 9.92369 12.2612 9.9716 12.289L20.1818 18.2137C20.2485 18.2524 20.332 18.2043 20.332 18.1272V6.1Z\"></path></svg>\r\n");
      out.write("								</div>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd\r\n");
      out.write("								class=\"ProjectItem__ProjectInfoDescription-sc-1vwy8z0-3 kbTFwt\">프로젝트를\r\n");
      out.write("								완수하기 위해 필요한 금액을 설정해주세요.</dd>\r\n");
      out.write("							<div class=\"ProjectItem__ProjectInfoNotice-sc-1vwy8z0-5 gJNjvn\">\r\n");
      out.write("								<div class=\"noticeTitle\">\r\n");
      out.write("									<div name=\"info-line-oval\"\r\n");
      out.write("										class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("										<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("											<path\r\n");
      out.write("												d=\"M21.5 23.1C21.5 23.0448 21.5448 23 21.6 23H26.4C26.4552 23 26.5 23.0448 26.5 23.1V33.9C26.5 33.9552 26.4552 34 26.4 34H21.6C21.5448 34 21.5 33.9552 21.5 33.9V23.1Z\"></path>\r\n");
      out.write("											<path\r\n");
      out.write("												d=\"M21 17C21 15.3431 22.3431 14 24 14C25.6569 14 27 15.3431 27 17C27 18.6569 25.6569 20 24 20C22.3431 20 21 18.6569 21 17Z\"></path>\r\n");
      out.write("											<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("												d=\"M24 40C32.8366 40 40 32.8366 40 24C40 15.1634 32.8366 8 24 8C15.1634 8 8 15.1634 8 24C8 32.8366 15.1634 40 24 40ZM24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\"></path></svg>\r\n");
      out.write("									</div>\r\n");
      out.write("									목표 금액 설정 시 꼭 알아두세요!\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<p>종료일까지 목표금액을 달성하지 못하면 후원자 결제가 진행되지 않습니다.</p>\r\n");
      out.write("									<p>종료 전 후원 취소를 대비해 10% 이상 초과 달성을 목표로 해주세요.</p>\r\n");
      out.write("									<p>제작비, 선물 배송비, 인건비, 예비 비용 등을 함께 고려해주세요.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</dl>\r\n");
      out.write("						<div class=\"ProjectItem__ProjectForms-sc-1vwy8z0-4 etypUj\">\r\n");
      out.write("							<div class=\"style__ProjectGoalFunding-sc-1mawbc1-14 kHILbl\">\r\n");
      out.write("								<p class=\"style__ProjectFormsTitle-sc-1mawbc1-10 fHMBHo\">목표금액</p>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"InputWithGuideAndLengthCheck__Wrapper-sc-9nmfrw-0 eCSxwJ\">\r\n");
      out.write("									<div\r\n");
      out.write("										class=\"InputWithGuideAndLengthCheck__InputWrapper-sc-9nmfrw-3 bBnjVq\">\r\n");
      out.write("										<span\r\n");
      out.write("											class=\"Input__InputWrapper-j7moqy-0 fOjsfs InputWithGuideAndLengthCheck__StyledInput-sc-9nmfrw-1 cNNWwa\"><input\r\n");
      out.write("											type=\"text\" inputmode=\"numeric\"\r\n");
      out.write("											placeholder=\"50만원 이상의 금액을 입력해주세요\" autocomplete=\"off\"\r\n");
      out.write("											autocapitalize=\"off\"\r\n");
      out.write("											class=\"Input__InnerInput-j7moqy-1 bfmNPl\" value=\"\">원</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div\r\n");
      out.write("										class=\"InputWithGuideAndLengthCheck__NoticeArea-sc-9nmfrw-4 ciHGYP\">\r\n");
      out.write("										<p\r\n");
      out.write("											class=\"InputWithGuideAndLengthCheck__GuideMessage-sc-9nmfrw-5 fduvas\"></p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"style__ProjectEstimatedAmount-sc-1mawbc1-15 qZZRG\">\r\n");
      out.write("									<div class=\"style__TotalAmount-sc-1mawbc1-16 OobSQ\">\r\n");
      out.write("										<span>목표 금액 달성 시 예상 수령액</span> <em>0원</em>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"style__FeesWrap-sc-1mawbc1-17 jFIOTU\">\r\n");
      out.write("										총 수수료<em>0원</em>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"style__FeesWrap-sc-1mawbc1-17 fsjSoz\">\r\n");
      out.write("										결제대행 수수료 (총 결제액의 3% + VAT)<em>0원</em>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"style__FeesWrap-sc-1mawbc1-17 fsjSoz\">\r\n");
      out.write("										Pro 요금제 수수료(총 결제 금액의 9% + VAT)<em>0원</em>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"ProjectItem__ProjectItemWrap-sc-1vwy8z0-0 loGysm\">\r\n");
      out.write("						<dl class=\"ProjectItem__ProjectInfo-sc-1vwy8z0-1 kwDByH\">\r\n");
      out.write("							<dt class=\"ProjectItem__ProjectInfoTitle-sc-1vwy8z0-2 gjLASS\">\r\n");
      out.write("								펀딩 일정\r\n");
      out.write("								<div name=\"asterisk-solid\"\r\n");
      out.write("									class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("									<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("										<path\r\n");
      out.write("											d=\"M20.332 6.1C20.332 6.04477 20.3768 6 20.432 6H27.1968C27.252 6 27.2968 6.04477 27.2968 6.1V18.2295C27.2968 18.3066 27.3803 18.3547 27.447 18.316L37.8336 12.289C37.8815 12.2612 37.9429 12.2777 37.9705 12.3257L41.3532 18.2144C41.3807 18.2622 41.3643 18.3231 41.3167 18.3507L31.0164 24.3277C30.95 24.3662 30.95 24.4622 31.0164 24.5007L40.8186 30.1886C40.8663 30.2163 40.8826 30.2772 40.8552 30.3249L37.4724 36.2137C37.4448 36.2617 37.3834 36.2782 37.3355 36.2504L27.447 30.5124C27.3803 30.4737 27.2968 30.5218 27.2968 30.5989V41.9C27.2968 41.9552 27.252 42 27.1968 42H20.432C20.3768 42 20.332 41.9552 20.332 41.9V30.7012C20.332 30.6241 20.2485 30.576 20.1818 30.6147L10.4697 36.2504C10.4218 36.2782 10.3604 36.2617 10.3328 36.2137L6.95002 30.3249C6.92259 30.2772 6.93892 30.2163 6.98654 30.1886L16.7888 24.5007C16.8552 24.4622 16.8552 24.3662 16.7888 24.3277L6.48846 18.3508C6.44084 18.3231 6.42451 18.2622 6.45194 18.2144L9.8347 12.3257C9.8623 12.2777 9.92369 12.2612 9.9716 12.289L20.1818 18.2137C20.2485 18.2524 20.332 18.2043 20.332 18.1272V6.1Z\"></path></svg>\r\n");
      out.write("								</div>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd\r\n");
      out.write("								class=\"ProjectItem__ProjectInfoDescription-sc-1vwy8z0-3 kbTFwt\">설정한\r\n");
      out.write("								일시가 되면 펀딩이 자동 시작됩니다. 펀딩 시작 전까지 날짜를 변경할 수 있고, 즉시 펀딩을 시작할 수도 있습니다.</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("						<div class=\"ProjectItem__ProjectForms-sc-1vwy8z0-4 etypUj\">\r\n");
      out.write("							<div class=\"style__ProjectFormsWrap-sc-1mawbc1-13 enzGlj\">\r\n");
      out.write("								<ol class=\"FundingPlan__FundingPlans-sc-1f9ovdu-1 foZtIs\">\r\n");
      out.write("									<li class=\"FundingPlan__FundingPlanItem-sc-1f9ovdu-2 eMrMYN\"><div\r\n");
      out.write("											class=\"FundingPlan__ProjectForms-sc-1f9ovdu-6 eghppi\">\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"FundingPlan__ProjectFormsHalf-sc-1f9ovdu-5 kjHLZy\">\r\n");
      out.write("												<p\r\n");
      out.write("													class=\"FundingPlan__ProjectFormsTitle-sc-1f9ovdu-0 gKXnxM\">시작일</p>\r\n");
      out.write("												<div\r\n");
      out.write("													class=\"EditorDatepicker__ProjectEditorDatePicker-sc-6ivupq-5 giJkqL\">\r\n");
      out.write("													<div class=\"react-datepicker-wrapper\">\r\n");
      out.write("														<div class=\"react-datepicker__input-container\">\r\n");
      out.write("															<button type=\"button\"\r\n");
      out.write("																class=\"EditorDatepicker__DateInput-sc-6ivupq-4 bWmuoo example-custom-input\">\r\n");
      out.write("																<div name=\"calendar-dot\"\r\n");
      out.write("																	class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("																	<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																		<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																			d=\"M43.5 13.6H4.5V11.8C4.5 10.4 5.6 9.3 7 9.3H41.2C42.6 9.3 43.7 10.4 43.7 11.8L43.5 13.6ZM43.5 41.1C43.5 42.5 42.4 43.6 41 43.6H6.9C5.5 43.6 4.4 42.5 4.4 41.1V16.1H43.5V41.1ZM41.1 6.9H38.6V2H36.1V6.9H11.8V2H9.3V6.9H6.9C4.2 6.9 2 9.1 2 11.8V41.1C2 43.8 4.2 46 6.9 46H41.1C43.8 46 46 43.8 46 41.1V11.8C46 9.1 43.8 6.9 41.1 6.9ZM11.2002 27.7001H14.9002C15.3002 27.7001 15.5002 27.4001 15.5002 27.0991V23.4001C15.5002 23.0001 15.2002 22.8001 14.9002 22.8001H11.2002C10.8002 22.8001 10.6002 23.1001 10.6002 23.4001V27.0001C10.5002 27.4001 10.8002 27.7001 11.2002 27.7001ZM25.9002 27.7001H22.2002C21.8002 27.7001 21.5002 27.4001 21.6002 27.0001V23.4001C21.6002 23.1001 21.8002 22.8001 22.2002 22.8001H25.9002C26.2002 22.8001 26.5002 23.0001 26.5002 23.4001V27.0991C26.5002 27.4001 26.3002 27.7001 25.9002 27.7001ZM33.2002 27.7001H36.9002C37.3002 27.7001 37.5002 27.4001 37.5002 27.0991V23.4001C37.5002 23.0001 37.2002 22.8001 36.9002 22.8001H33.2002C32.8002 22.8001 32.5992 23.1001 32.5992 23.4001V27.0001C32.5002 27.4001 32.8002 27.7001 33.2002 27.7001ZM14.9002 37.4999H11.2002C10.8002 37.4999 10.5002 37.1999 10.6002 36.8999V33.1999C10.6002 32.8999 10.8002 32.5999 11.2002 32.5999H14.9002C15.2002 32.5999 15.5002 32.7999 15.5002 33.1999V36.8999C15.5002 37.1999 15.3002 37.4999 14.9002 37.4999ZM22.2002 37.4999H25.9002C26.3002 37.4999 26.5002 37.1999 26.5002 36.8999V33.1999C26.5002 32.7999 26.2002 32.5999 25.9002 32.5999H22.2002C21.8002 32.5999 21.6002 32.8999 21.6002 33.1999V36.8999C21.5002 37.1999 21.8002 37.4999 22.2002 37.4999ZM36.9002 37.4999H33.2002C32.8002 37.4999 32.5002 37.1999 32.5992 36.8999V33.1999C32.5992 32.8999 32.8002 32.5999 33.2002 32.5999H36.9002C37.2002 32.5999 37.5002 32.7999 37.5002 33.1999V36.8999C37.5002 37.1999 37.3002 37.4999 36.9002 37.4999Z\"></path></svg>\r\n");
      out.write("																</div>\r\n");
      out.write("																시작 날짜를 선택해주세요\r\n");
      out.write("															</button>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"FundingPlan__ProjectFormsHalf-sc-1f9ovdu-5 kjHLZy\">\r\n");
      out.write("												<p\r\n");
      out.write("													class=\"FundingPlan__ProjectFormsTitle-sc-1f9ovdu-0 gKXnxM\">시작\r\n");
      out.write("													시간</p>\r\n");
      out.write("												<div class=\"SelectWithSingle__Wrapper-sc-1eotg4s-1 fzVHyd\">\r\n");
      out.write("													<span\r\n");
      out.write("														class=\"Input__InputWrapper-j7moqy-0 LuJNQ SelectWithSingle__Selected-sc-1eotg4s-3 intylJ\"\r\n");
      out.write("														readonly=\"\" disabled=\"\"><input disabled=\"\"\r\n");
      out.write("														readonly=\"\" type=\"text\" inputmode=\"text\"\r\n");
      out.write("														autocomplete=\"off\" autocapitalize=\"off\"\r\n");
      out.write("														class=\"Input__InnerInput-j7moqy-1 bfmNPl\"\r\n");
      out.write("														value=\"시작 시간을 선택해주세요\">\r\n");
      out.write("													<div name=\"arrow2-down\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M2 14.4065C2 13.1363 3.09843 12.0615 4.39657 12.0615C4.99571 12.0615 5.59485 12.257 6.09414 12.7455L23.9685 29.4526L41.843 12.6478C42.8415 11.7684 44.3394 11.7684 45.338 12.7455C46.2367 13.7226 46.2367 15.1882 45.2381 16.0676L23.9685 36L2.79886 16.0676C2.29957 15.6767 2 14.9928 2 14.4065Z\"></path></svg>\r\n");
      out.write("														</div></span>\r\n");
      out.write("													<div></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div type=\"p4\" color=\"#e53c41\"\r\n");
      out.write("													class=\"Text-sc-1cqgvse-0 SelectWithSingle__ErrorMessage-sc-1eotg4s-0 jQwQu gpuBnE\"></div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"FundingPlan__FundingTerm-sc-1f9ovdu-3 cFBWEo\">\r\n");
      out.write("											<p class=\"FundingPlan__ProjectFormsTitle-sc-1f9ovdu-0 gKXnxM\">펀딩\r\n");
      out.write("												기간</p>\r\n");
      out.write("											최대 60일\r\n");
      out.write("										</div></li>\r\n");
      out.write("									<li class=\"FundingPlan__FundingPlanItem-sc-1f9ovdu-2 eMrMYN\"><div\r\n");
      out.write("											class=\"FundingPlan__ProjectTooltip-sc-1f9ovdu-4 hkXrPY\">\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"LabelWithAreaTooltip__LabelWrapper-sc-16u328b-2 eCiCMa\">\r\n");
      out.write("												<button type=\"button\"\r\n");
      out.write("													class=\"LabelWithAreaTooltip__Label-sc-16u328b-1 joiGLy\">\r\n");
      out.write("													<p>종료일</p>\r\n");
      out.write("													<em><div name=\"question-line-oval\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path\r\n");
      out.write("																	d=\"M21 32C21 30.3431 22.3431 29 24 29C25.6569 29 27 30.3431 27 32C27 33.6569 25.6569 35 24 35C22.3431 35 21 33.6569 21 32Z\"></path>\r\n");
      out.write("																<path\r\n");
      out.write("																	d=\"M21.9348 26.9132C21.9415 26.9622 21.9838 27 22.0333 27H26.0227C26.0817 27 26.1276 26.9473 26.1235 26.8885C25.8753 23.3015 30.3992 22.3538 30.3992 18.5189C30.3992 14.6445 26.5708 13 24.4315 13C22.3011 13 19.2378 13 17.224 17.9579C17.2092 17.9945 17.2169 18.0376 17.2444 18.066L19.8 20.704C19.8484 20.7539 19.9321 20.7395 19.9628 20.6771C21.2872 17.9873 22.4684 16.9859 23.8375 16.9859C24.6647 16.9859 25.7817 17.627 25.7817 18.8534C25.7817 21.1235 21.3597 22.6862 21.9348 26.9132Z\"></path>\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M24 40C32.8366 40 40 32.8366 40 24C40 15.1634 32.8366 8 24 8C15.1634 8 8 15.1634 8 24C8 32.8366 15.1634 40 24 40ZM24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\"></path></svg>\r\n");
      out.write("														</div></em>\r\n");
      out.write("												</button>\r\n");
      out.write("												<div\r\n");
      out.write("													class=\"LabelWithAreaTooltip__Tooltip-sc-16u328b-3 dBcuBc\">\r\n");
      out.write("													선택하신 종료일 다음 날 0시에 펀딩이 종료됩니다.<em class=\"close\"><div\r\n");
      out.write("															name=\"close-1\" class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M45.1766 41.0846L28.1097 24.0186L45.1766 6.95266C46.2744 5.85485 46.2744 4.05843 45.1766 2.86082C44.0778 1.66321 42.2824 1.76401 41.0838 2.86082L24.0189 19.9268L6.95301 2.86082C5.8552 1.76401 4.05879 1.76401 2.86119 2.86082C1.66358 3.95863 1.76338 5.75605 2.86119 6.95266L19.9271 24.0186L2.86119 41.0846C1.76338 42.1834 1.76338 43.9788 2.86119 45.1774C3.95899 46.2742 5.7554 46.2742 6.95301 45.1774L24.0189 28.1104L41.0838 45.1774C42.1826 46.2742 43.979 46.2742 45.1766 45.1774C46.2744 43.9788 46.2744 42.1834 45.1766 41.0846Z\"></path></svg>\r\n");
      out.write("														</div></em>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"EditorDatepicker__ProjectEditorDatePicker-sc-6ivupq-5 giJkqL\">\r\n");
      out.write("											<div class=\"react-datepicker-wrapper\">\r\n");
      out.write("												<div class=\"react-datepicker__input-container\">\r\n");
      out.write("													<button type=\"button\"\r\n");
      out.write("														class=\"EditorDatepicker__DateInput-sc-6ivupq-4 bWmuoo example-custom-input\">\r\n");
      out.write("														<div name=\"calendar-dot\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M43.5 13.6H4.5V11.8C4.5 10.4 5.6 9.3 7 9.3H41.2C42.6 9.3 43.7 10.4 43.7 11.8L43.5 13.6ZM43.5 41.1C43.5 42.5 42.4 43.6 41 43.6H6.9C5.5 43.6 4.4 42.5 4.4 41.1V16.1H43.5V41.1ZM41.1 6.9H38.6V2H36.1V6.9H11.8V2H9.3V6.9H6.9C4.2 6.9 2 9.1 2 11.8V41.1C2 43.8 4.2 46 6.9 46H41.1C43.8 46 46 43.8 46 41.1V11.8C46 9.1 43.8 6.9 41.1 6.9ZM11.2002 27.7001H14.9002C15.3002 27.7001 15.5002 27.4001 15.5002 27.0991V23.4001C15.5002 23.0001 15.2002 22.8001 14.9002 22.8001H11.2002C10.8002 22.8001 10.6002 23.1001 10.6002 23.4001V27.0001C10.5002 27.4001 10.8002 27.7001 11.2002 27.7001ZM25.9002 27.7001H22.2002C21.8002 27.7001 21.5002 27.4001 21.6002 27.0001V23.4001C21.6002 23.1001 21.8002 22.8001 22.2002 22.8001H25.9002C26.2002 22.8001 26.5002 23.0001 26.5002 23.4001V27.0991C26.5002 27.4001 26.3002 27.7001 25.9002 27.7001ZM33.2002 27.7001H36.9002C37.3002 27.7001 37.5002 27.4001 37.5002 27.0991V23.4001C37.5002 23.0001 37.2002 22.8001 36.9002 22.8001H33.2002C32.8002 22.8001 32.5992 23.1001 32.5992 23.4001V27.0001C32.5002 27.4001 32.8002 27.7001 33.2002 27.7001ZM14.9002 37.4999H11.2002C10.8002 37.4999 10.5002 37.1999 10.6002 36.8999V33.1999C10.6002 32.8999 10.8002 32.5999 11.2002 32.5999H14.9002C15.2002 32.5999 15.5002 32.7999 15.5002 33.1999V36.8999C15.5002 37.1999 15.3002 37.4999 14.9002 37.4999ZM22.2002 37.4999H25.9002C26.3002 37.4999 26.5002 37.1999 26.5002 36.8999V33.1999C26.5002 32.7999 26.2002 32.5999 25.9002 32.5999H22.2002C21.8002 32.5999 21.6002 32.8999 21.6002 33.1999V36.8999C21.5002 37.1999 21.8002 37.4999 22.2002 37.4999ZM36.9002 37.4999H33.2002C32.8002 37.4999 32.5002 37.1999 32.5992 36.8999V33.1999C32.5992 32.8999 32.8002 32.5999 33.2002 32.5999H36.9002C37.2002 32.5999 37.5002 32.7999 37.5002 33.1999V36.8999C37.5002 37.1999 37.3002 37.4999 36.9002 37.4999Z\"></path></svg>\r\n");
      out.write("														</div>\r\n");
      out.write("														종료 날짜를 선택해주세요\r\n");
      out.write("													</button>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div></li>\r\n");
      out.write("									<li class=\"FundingPlan__FundingPlanItem-sc-1f9ovdu-2 eMrMYN\"><div\r\n");
      out.write("											class=\"FundingPlan__ProjectTooltip-sc-1f9ovdu-4 hkXrPY\">\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"LabelWithAreaTooltip__LabelWrapper-sc-16u328b-2 eCiCMa\">\r\n");
      out.write("												<button type=\"button\"\r\n");
      out.write("													class=\"LabelWithAreaTooltip__Label-sc-16u328b-1 joiGLy\">\r\n");
      out.write("													<p>후원자 결제 종료</p>\r\n");
      out.write("													<em><div name=\"question-line-oval\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path\r\n");
      out.write("																	d=\"M21 32C21 30.3431 22.3431 29 24 29C25.6569 29 27 30.3431 27 32C27 33.6569 25.6569 35 24 35C22.3431 35 21 33.6569 21 32Z\"></path>\r\n");
      out.write("																<path\r\n");
      out.write("																	d=\"M21.9348 26.9132C21.9415 26.9622 21.9838 27 22.0333 27H26.0227C26.0817 27 26.1276 26.9473 26.1235 26.8885C25.8753 23.3015 30.3992 22.3538 30.3992 18.5189C30.3992 14.6445 26.5708 13 24.4315 13C22.3011 13 19.2378 13 17.224 17.9579C17.2092 17.9945 17.2169 18.0376 17.2444 18.066L19.8 20.704C19.8484 20.7539 19.9321 20.7395 19.9628 20.6771C21.2872 17.9873 22.4684 16.9859 23.8375 16.9859C24.6647 16.9859 25.7817 17.627 25.7817 18.8534C25.7817 21.1235 21.3597 22.6862 21.9348 26.9132Z\"></path>\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M24 40C32.8366 40 40 32.8366 40 24C40 15.1634 32.8366 8 24 8C15.1634 8 8 15.1634 8 24C8 32.8366 15.1634 40 24 40ZM24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\"></path></svg>\r\n");
      out.write("														</div></em>\r\n");
      out.write("												</button>\r\n");
      out.write("												<div\r\n");
      out.write("													class=\"LabelWithAreaTooltip__Tooltip-sc-16u328b-3 dBcuBc\">\r\n");
      out.write("													<div>프로젝트가 성공하면 펀딩 종료 다음 날 후원금이 결제됩니다. 결제가 이루어지지 않은\r\n");
      out.write("														경우 24시간 간격으로 7일 동안 결제를 시도합니다.</div>\r\n");
      out.write("													<em class=\"close\"><div name=\"close-1\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M45.1766 41.0846L28.1097 24.0186L45.1766 6.95266C46.2744 5.85485 46.2744 4.05843 45.1766 2.86082C44.0778 1.66321 42.2824 1.76401 41.0838 2.86082L24.0189 19.9268L6.95301 2.86082C5.8552 1.76401 4.05879 1.76401 2.86119 2.86082C1.66358 3.95863 1.76338 5.75605 2.86119 6.95266L19.9271 24.0186L2.86119 41.0846C1.76338 42.1834 1.76338 43.9788 2.86119 45.1774C3.95899 46.2742 5.7554 46.2742 6.95301 45.1774L24.0189 28.1104L41.0838 45.1774C42.1826 46.2742 43.979 46.2742 45.1766 45.1774C46.2744 43.9788 46.2744 42.1834 45.1766 41.0846Z\"></path></svg>\r\n");
      out.write("														</div></em>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>종료일 다음 날부터 7일</li>\r\n");
      out.write("									<li class=\"FundingPlan__FundingPlanItem-sc-1f9ovdu-2 eMrMYN\"><div\r\n");
      out.write("											class=\"FundingPlan__ProjectTooltip-sc-1f9ovdu-4 hkXrPY\">\r\n");
      out.write("											<div\r\n");
      out.write("												class=\"LabelWithAreaTooltip__LabelWrapper-sc-16u328b-2 eCiCMa\">\r\n");
      out.write("												<button type=\"button\"\r\n");
      out.write("													class=\"LabelWithAreaTooltip__Label-sc-16u328b-1 joiGLy\">\r\n");
      out.write("													<p>정산일</p>\r\n");
      out.write("													<em><div name=\"question-line-oval\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path\r\n");
      out.write("																	d=\"M21 32C21 30.3431 22.3431 29 24 29C25.6569 29 27 30.3431 27 32C27 33.6569 25.6569 35 24 35C22.3431 35 21 33.6569 21 32Z\"></path>\r\n");
      out.write("																<path\r\n");
      out.write("																	d=\"M21.9348 26.9132C21.9415 26.9622 21.9838 27 22.0333 27H26.0227C26.0817 27 26.1276 26.9473 26.1235 26.8885C25.8753 23.3015 30.3992 22.3538 30.3992 18.5189C30.3992 14.6445 26.5708 13 24.4315 13C22.3011 13 19.2378 13 17.224 17.9579C17.2092 17.9945 17.2169 18.0376 17.2444 18.066L19.8 20.704C19.8484 20.7539 19.9321 20.7395 19.9628 20.6771C21.2872 17.9873 22.4684 16.9859 23.8375 16.9859C24.6647 16.9859 25.7817 17.627 25.7817 18.8534C25.7817 21.1235 21.3597 22.6862 21.9348 26.9132Z\"></path>\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M24 40C32.8366 40 40 32.8366 40 24C40 15.1634 32.8366 8 24 8C15.1634 8 8 15.1634 8 24C8 32.8366 15.1634 40 24 40ZM24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\"></path></svg>\r\n");
      out.write("														</div></em>\r\n");
      out.write("												</button>\r\n");
      out.write("												<div\r\n");
      out.write("													class=\"LabelWithAreaTooltip__Tooltip-sc-16u328b-3 dBcuBc\">\r\n");
      out.write("													모금액은 후원자 결제 종료 다음 날부터 영업일 기준(주말 및 공휴일 제외) 7일째 되는 날 입금됩니다.<em\r\n");
      out.write("														class=\"close\"><div name=\"close-1\"\r\n");
      out.write("															class=\"Icon__SVGICON-sc-1xkf9cp-0 ccxeYs\">\r\n");
      out.write("															<svg viewBox=\"0 0 48 48\">\r\n");
      out.write("																<path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\r\n");
      out.write("																	d=\"M45.1766 41.0846L28.1097 24.0186L45.1766 6.95266C46.2744 5.85485 46.2744 4.05843 45.1766 2.86082C44.0778 1.66321 42.2824 1.76401 41.0838 2.86082L24.0189 19.9268L6.95301 2.86082C5.8552 1.76401 4.05879 1.76401 2.86119 2.86082C1.66358 3.95863 1.76338 5.75605 2.86119 6.95266L19.9271 24.0186L2.86119 41.0846C1.76338 42.1834 1.76338 43.9788 2.86119 45.1774C3.95899 46.2742 5.7554 46.2742 6.95301 45.1774L24.0189 28.1104L41.0838 45.1774C42.1826 46.2742 43.979 46.2742 45.1766 45.1774C46.2744 43.9788 46.2744 42.1834 45.1766 41.0846Z\"></path></svg>\r\n");
      out.write("														</div></em>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>후원자 결제 종료 다음 날부터 7영업일</li>\r\n");
      out.write("								</ol>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
